sonar.projectKey=Goaname
sonar.projectName=Goaname
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/Migrations/**,**/*.js,**/*.css,**/*.html
